#!/usr/bin/env python

from argparse import ArgumentParser

import snfpipe


IAUC_FNAME = "/project/projectdirs/snfactry/raw/iauc/Supernovae.html"

iauc_targets = snfpipe.read_iauc_targets(IAUC_FNAME)
