#!/bin/bash

REMOTE_IMAGES_PREFIX=/sps/snovae/SRBregister/hawaii
REMOTE_LOGS_PREFIX=/sps/snovae/SRBregister/log

PROJECT_IMAGES_PREFIX=/project/projectdirs/snfactry/raw/images
PROJECT_LOGS_PREFIX=/project/projectdirs/snfactry/raw/logs

function joinstrings { local IFS="$1"; shift; echo "$*"; }

if [[ $# -ne 2 || $1 == "-h" || $1 == "--help" || $2 == "-h" || $2 == "--help" ]]; then
    echo "usage: pull-raw-data <year> <nightpattern>"
    echo ""
    echo "  Pull raw data from CC to /project."
    echo "  <nightpattern> can be a single night, such as 016, or a shell "
    echo "  pattern such as \"01*\" (be sure to use quotes to avoid shell "
    echo "  expansion: the pattern is passed to rsync)."
    exit
fi

if [[ -z "$SNF_CC_USER" || -z "$SNF_CC_SERVER" ]]; then
    echo "ERROR: must set SNF_CC_USER and SNF_CC_SERVER environment variables"
    exit
fi


year=$1
nightpattern=$2

# pull logs
(set -x; rsync -rtvz ${SNF_CC_USER}@${SNF_CC_SERVER}:${REMOTE_LOGS_PREFIX}/${year}/${nightpattern} ${PROJECT_LOGS_PREFIX}/${year})

if [[ $? -ne 0 ]]; then
    echo "ERROR: rsync error" >&2
    exit 1
fi     

# pull images
(set -x; rsync -rtvz ${SNF_CC_USER}@${SNF_CC_SERVER}:${REMOTE_IMAGES_PREFIX}/${year}/${nightpattern} ${PROJECT_IMAGES_PREFIX}/${year})

if [[ $? -ne 0 ]]; then
    echo "ERROR: rsync error" >&2
    exit 1
fi
